PRAGMA foreign_keys=OFF;
BEGIN TRANSACTION;
CREATE TABLE INSTITUTE_LIST (
    "ID" TEXT PRIMARY KEY NOT NULL UNIQUE,
    "NAMES" TEXT NOT NULL,
    "SITES" TEXT NOT NULL,
    "LOCATIONS" TEXT NOT NULL,
    "SOURCES" TEXT NOT NULL,
    "PERSECUTION" TEXT NOT NULL,
    "EVIDENCES" TEXT NOT NULL,
    "SCALE" TEXT NOT NULL,
    "CHECKED" TEXT NOT NULL
);
INSERT INTO INSTITUTE_LIST VALUES('295CABEE','昭山素质教育','https://www.lzszjyxx.com/','湖南湘潭市岳塘区高峰村坳上组青少年素质教育学校','ASaferChina (channel)@Telegram','TRUE','https://web.archive.org/web/20231111060020/https://www.msn.com/en-au/news/other/inside-china-s-lgbtqia-re-education-camps-survivors-claim-shock-treatment-and-beatings/ar-AA18xfV9','UNKNOWN','FALSE');
INSERT INTO INSTITUTE_LIST VALUES('82E09EFB','贤德素质教育学校','http://www.aishangzs.com/ || http://texunschool.com/ || http://www.ahedu.net.cn/','湖南省长沙市','ASaferChina (channel)@Telegram','TRUE','https://web.archive.org/web/20231111060020/https://www.msn.com/en-au/news/other/inside-china-s-lgbtqia-re-education-camps-survivors-claim-shock-treatment-and-beatings/ar-AA18xfV9','UNKNOWN','FALSE');
INSERT INTO INSTITUTE_LIST VALUES('E99222D4','北海市愉达复教育咨询有限公司','http://www.ydf-edu.com/','广西北海市银海区银滩风景区','ASaferChina (channel)@Telegram','UNKNOWN','NONE','UNKNOWN','FALSE');
INSERT INTO INSTITUTE_LIST VALUES('0F1465F8','重庆锦辉青少年素质教育学校','http://www.cqtx110.com/','重庆市沙坪坝区中梁镇后槽路西50米','ASaferChina (channel)@Telegram','UNKNOWN','NONE','UNKNOWN','FALSE');
INSERT INTO INSTITUTE_LIST VALUES('5A589D6B','长沙湘越中学','https://www.xiangyuezhongxue.com/','湖南省长沙市长沙县春华镇春华山村88号','ASaferChina (channel)@Telegram || CTSN','UNKNOWN','NONE','300','FALSE');
INSERT INTO INSTITUTE_LIST VALUES('1F185186','河源弘毅素质教育创新研究基地','http://www.ttxsjyjd.com/','广东省河源市紫金县义容镇西平村石下小学侧边办公楼','ASaferChina (channel)@Telegram','UNKNOWN','NONE','UNKNOWN','FALSE');
INSERT INTO INSTITUTE_LIST VALUES('6543A0CA','山东正心教育培训学校有限公司','http://www.zhengxinedu.com/','山东省潍坊市峡山区岞山街道岞山第二小学北邻','ASaferChina (channel)@Telegram || 寒涟漪创建的扭转机构名单','TRUE','https://web.archive.org/web/20231111060020/https://www.msn.com/en-au/news/other/inside-china-s-lgbtqia-re-education-camps-survivors-claim-shock-treatment-and-beatings/ar-AA18xfV9','200','FALSE');
INSERT INTO INSTITUTE_LIST VALUES('07A4148A','睿智教育专门学校','http://www.999jwy.com/','湖南省长沙市望城区高塘岭街道新阳村','ASaferChina (channel)@Telegram || CTSN','UNKNOWN','NONE','200','FALSE');
INSERT INTO INSTITUTE_LIST VALUES('9D1650F5','徐州励志少年军校 || 徐州西正教育 || 徐州塑仁教育','https://weibo.com/u/5294085683/','UNKNOWN','ASaferChina (channel)@Telegram','UNKNOWN','NONE','UNKNOWN','FALSE');
INSERT INTO INSTITUTE_LIST VALUES('0E491293','雅圣思','(无法正常访问)http://www.yashengsi.com/','UNKNOWN','ASaferChina (channel)@Telegram','TRUE','https://www.voachinese.com/a/china-private-schools-accused-of-abusing-students-20230130/6939487.html','UNKNOWN','FALSE');
INSERT INTO INSTITUTE_LIST VALUES('96B91820','少林文武教育','http://www.shaolinxiao.com/','湖南娄底市水洞底镇中心村(距市政府8公里)','百度搜索','UNKNOWN','NONE','UNKNOWN','FALSE');
INSERT INTO INSTITUTE_LIST VALUES('AC86F966','南华青少年素质教育学校','http://www.csnhjyxx.com/','长沙市望城区丁字派出所旁','百度搜索','UNKNOWN','NONE','UNKNOWN','FALSE');
INSERT INTO INSTITUTE_LIST VALUES('6385D46A','严德教育','https://www.hngengwu.cn/','UNKNOWN','百度搜索','UNKNOWN','NONE','UNKNOWN','FALSE');
INSERT INTO INSTITUTE_LIST VALUES('D6663E0C','郑州思图励志教育学校','http://www.edandao.cn/','湖北省随州市随县柳树塆6组10号思图教育大别山区社会实践基地','百度搜索 || CTSN','UNKNOWN','NONE','300+','FALSE');
INSERT INTO INSTITUTE_LIST VALUES('85E0E946','至善教育','https://www.pannijy.cn/','湖南省长沙市开福区沙坪湘绣小镇沙坪中学','百度搜索','UNKNOWN','NONE','UNKNOWN','FALSE');
INSERT INTO INSTITUTE_LIST VALUES('EECC6C27','新叶教育 || 广西玉林市新叶教育','https://ylsxyjy.com/','玉林校区: 广西玉林市仁东周村林园内','“相关证据”中所示报道 || 寒涟漪创建的扭转机构名单','TRUE','https://web.archive.org/web/20231111060020/https://www.msn.com/en-au/news/other/inside-china-s-lgbtqia-re-education-camps-survivors-claim-shock-treatment-and-beatings/ar-AA18xfV9','UNKNOWN','FALSE');
INSERT INTO INSTITUTE_LIST VALUES('506EAEA6','英高特素质教育学校','http://www.hnjwy.org.cn/','湖南省长沙市','“相关证据”中所示报道','TRUE','https://web.archive.org/web/20231111060020/https://www.msn.com/en-au/news/other/inside-china-s-lgbtqia-re-education-camps-survivors-claim-shock-treatment-and-beatings/ar-AA18xfV9','UNKNOWN','FALSE');
INSERT INTO INSTITUTE_LIST VALUES('A7C89F27','山东网康教育培训学校','http://www.jjerw.com/b/sdwkjypxxxwxevrs/','总部(市中校区): 二环南路3号','“相关证据”中所示报道','TRUE','https://web.archive.org/web/20231111060020/https://www.msn.com/en-au/news/other/inside-china-s-lgbtqia-re-education-camps-survivors-claim-shock-treatment-and-beatings/ar-AA18xfV9','UNKNOWN','FALSE');
INSERT INTO INSTITUTE_LIST VALUES('C6DEF13F','长沙泽邦青少年培训学校','https://zebangedu.com/','湖南省长沙市长沙县安沙镇鼎功桥村68号','百度搜索 || CTSN','UNKNOWN','NONE','100','FALSE');
INSERT INTO INSTITUTE_LIST VALUES('9FB45AB6','武汉正苗启德叛逆期管教学校 || 正苗启德青少年特训学校 || 湖北正苗启德青少年特训学校','https://www.wangyinxuexiao.com/ || https://www.zmqd.cn/ || http://www.qidetexun.com.cn/','湖北省孝感市汉川市马口镇大咀村 || 湖北校区: 湖北省武汉市蔡甸与汉川交汇处(离汉川高铁站5公里) || 湖南校区: 湖南省长沙市开福区沙坪湘绣城启德励志教育学校 || 河南校区: 河南省郑州市巩义正苗启德教育学校 || 浙江校区: 浙江省丽水市缙云县启德特训学校 浙江省丽水市缙云县大桥北路293号','百度搜索 || 寒涟漪创建的扭转机构名单 || CTSN','UNKNOWN','NONE','1000+','FALSE');
INSERT INTO INSTITUTE_LIST VALUES('FD05CB57','黄冈纽特教育','UNKNOWN','黄冈市黄州区陈策楼镇王家岗教学点','寒涟漪创建的扭转机构名单','TRUE','PENDING','UNKNOWN','FALSE');
INSERT INTO INSTITUTE_LIST VALUES('F45FC209','武汉纽特青少年戒网瘾学校 || 纽特心理','http://www.jwyw.org/ || http://www.nt-edu.com/','湖北校区: 湖北省武汉市洪山区落雁路纽特学校(沙湖果批公交站对面)','百度搜索 || 寒涟漪创建的扭转机构名单','UNKNOWN','NONE','UNKNOWN','FALSE');
INSERT INTO INSTITUTE_LIST VALUES('86CBE30E','正德叛逆孩子学校 || 正德青少年管教学校','https://www.75tx.com/ || https://www.kashangkaxia.com/ || https://www.jiangnanxueyuan.com/','湖北省汉川市叛逆孩子学校 || 湖北省孝感市汉川市马口镇','百度搜索','UNKNOWN','NONE','UNKNOWN','FALSE');
INSERT INTO INSTITUTE_LIST VALUES('E535DB3C','西安重生素质教育学校 || 西安重生训练基地','https://sxhdcs.com/','西安市长安区杜曲镇西杨万村生产一路10号-西安重生青少年综合素质拓展基地 || 西安市长安区三府衙村西安重生综合训练基地','“相关证据”中所示知乎回答','UNKNOWN','https://www.zhihu.com/question/24332871/answer/549042493','UNKNOWN','FALSE');
INSERT INTO INSTITUTE_LIST VALUES('A8C922AF','华育农耕实践教育基地 || 重庆华育素质教育基地 || 重庆华励素质教育 || 重庆华育素质教育','https://www.hlszjy.com/','学校地址: 青少年农耕实践教育基地','“相关证据”中所示知乎回答','UNKNOWN','https://zhuanlan.zhihu.com/p/602713084','UNKNOWN','FALSE');
INSERT INTO INSTITUTE_LIST VALUES('8A942776','清德教育','http://www.qsn580.com/','长沙校区: 湖南长沙市望城区乔口镇; 湘潭校区: 湖南湘潭市岳塘区昭山镇; 岳阳校区: 岳阳市湘阴县岭北镇; 湖北校区: 湖北黄冈市黄州区; 安徽校区: 宣城市绩溪县','B站视频(BV1js4y1s7a1)的评论区','UNKNOWN','NONE','UNKNOWN','FALSE');
INSERT INTO INSTITUTE_LIST VALUES('6EEA89E8','昆明丑小鸭中学','https://hhzedu.net/','昆明市宜良县匡远镇瑞星村','B站视频(BV1J84y1p7mr)的评论区','UNKNOWN','NONE','UNKNOWN','FALSE');
INSERT INTO INSTITUTE_LIST VALUES('B4AD23C3','长沙县杰龙青少年特训学校 || 杰龙特训 || 杰龙青少年特训学校','http://csccjy.com/ || https://www.jielongtx.com/','湖南省长沙县江背镇乌川湖村拱桥组115号','B站视频(BV1J84y1p7mr)的评论区 || 知乎搜索->https://zhuanlan.zhihu.com/p/550644396 || CTSN','UNKNOWN','NONE','400+','FALSE');
INSERT INTO INSTITUTE_LIST VALUES('B44C8154','重庆胤呈青少年训练营','https://cqsztxy.com/','重庆市南川区文凤镇庆岩居委会','B站视频(BV1J84y1p7mr)的评论区','UNKNOWN','NONE','UNKNOWN','FALSE');
INSERT INTO INSTITUTE_LIST VALUES('726D1CBE','昆明安宁市好孩子教育培训学校','http://www.kmhhz.com/','昆明安宁市嵩华路4-28号','B站视频(BV1J84y1p7mr)的评论区','UNKNOWN','NONE','UNKNOWN','FALSE');
INSERT INTO INSTITUTE_LIST VALUES('BA4356C2','河南慧诺特国际教育','http://www.huinuote.com/','联系地址: 河南省郑州市新密市富民东路168号','B站视频(BV1J84y1p7mr)的评论区','UNKNOWN','NONE','UNKNOWN','FALSE');
INSERT INTO INSTITUTE_LIST VALUES('681745C1','启德青少年励志成长学校','http://www.shanghaitexun.org.cn/','总部地址: 湖南省长沙市区望城区','百度搜索','UNKNOWN','NONE','UNKNOWN','FALSE');
INSERT INTO INSTITUTE_LIST VALUES('6E114C2C','济南德泓教育','https://www.jndhjyzx.com/','山东省济南市历城区东郭而庄村','百度搜索->https://zhuanlan.zhihu.com/p/567280444 || CTSN','TRUE','NONE','UNKNOWN','FALSE');
INSERT INTO INSTITUTE_LIST VALUES('178124F5','集结号青少年心理教育基地','http://www.jjhhrjyjd.com/','公司地址: 河南省漯河市市辖区城乡一体化示范区姬石镇罗庄小学99号','B站视频(BV1Aj411u7Dd)的评论区','UNKNOWN','NONE','UNKNOWN','FALSE');
INSERT INTO INSTITUTE_LIST VALUES('3E27B9A4','广东麦田教育','https://www.gdmtjy.com/','学校坐落于广东省清远市清新区太平镇','网友私信 || 寒涟漪创建的扭转机构名单','TRUE','PENDING','UNKNOWN','FALSE');
INSERT INTO INSTITUTE_LIST VALUES('1A949627','广州育明','http://www.yuming521.com/','中心地址: 广州市从化区鳌头镇中塘村98号(中塘村委旁原富力小学)','网友私信','UNKNOWN','PENDING','UNKNOWN','FALSE');
INSERT INTO INSTITUTE_LIST VALUES('653460C7','引领星培训教育学校 || 引领星素质教育学校 || 团风引领星培训学校','http://www.ylxszjy.com/','地址: 黄冈市团风县淋山河镇泡树岗村 城东公路与Y003交叉口北','寒涟漪创建的扭转机构名单->DuckDuckGo搜索 || CTSN','TRUE','PENDING','150','FALSE');
INSERT INTO INSTITUTE_LIST VALUES('72BDED79','河南护航教育 || 河南护航青少年综合素质教育基地 || 护航学校','https://www.qianxuew.com/henanhuhangjiaoyu','新乡校区: 河南省新乡市原阳县白庙社区188号','寒涟漪创建的扭转机构名单','TRUE','PENDING','UNKNOWN','FALSE');
INSERT INTO INSTITUTE_LIST VALUES('63F7097C','岳阳市君山区善一培训学校有限公司','UNKNOWN','湖南省岳阳市君山区广兴洲镇黄安村四组善一学校院','寒涟漪创建的扭转机构名单 || CTSN','TRUE','PENDING','UNKNOWN','FALSE');
INSERT INTO INSTITUTE_LIST VALUES('F8877B2A','淄博德志学校','UNKNOWN','山东省淄博市桓台县团结路','寒涟漪创建的扭转机构名单 || CTSN','TRUE','PENDING','300','FALSE');
INSERT INTO INSTITUTE_LIST VALUES('36CE893C','河南省新密市伏羲山若水教育 || 若水教育基地','(无法正常访问)http://ruoshuids.com/','新密市伏羲山尖山村若水教育','寒涟漪创建的扭转机构名单 || (→)百度搜索','TRUE','PENDING','UNKNOWN','FALSE');
INSERT INTO INSTITUTE_LIST VALUES('6613C021','上海关兴教育 || 上海市浦东新区关兴教育培训中心 || 上海关兴教育科技有限公司','https://www.shgxjy.com/','本培训中心座落于: 上海市浦东新区航头镇航都路12号','网友私信','UNKNOWN','NONE','UNKNOWN','FALSE');
INSERT INTO INSTITUTE_LIST VALUES('E649866A','重庆市大足育新学校','http://www.cqyx999.com/','重庆市大足区团结路世纪阳光水岸东南侧约150米','https://twitter.com/IrohaS511/status/1641669213260759040','TRUE','PENDING','UNKNOWN','FALSE');
INSERT INTO INSTITUTE_LIST VALUES('B8CAC0EB','湖南省湘潭市岳塘区素质教育学校','(推测而得)http://www.hnqsnszjy.com/','(推测而得)湘潭市岳塘区青少年素质教育培训学校位于长株潭城市群中心区域位置—绿心昭山','https://twitter.com/Just_A_Mumei/status/1641026655366926338→百度搜索','TRUE','https://twitter.com/Just_A_Mumei/status/1641026655366926338','UNKNOWN','FALSE');
INSERT INTO INSTITUTE_LIST VALUES('7914D3AB','合肥新目标素质教育学校','(无法正常访问)http://www.ahxmb.com/','UNKNOWN','https://tieba.baidu.com/p/8311776125→百度搜索→https://tieba.baidu.com/p/8154831979','UNKNOWN','https://tieba.baidu.com/p/8154831979','UNKNOWN','FALSE');
INSERT INTO INSTITUTE_LIST VALUES('9C17E447','宇凰德育 || 宇凰德育教育基地 || 湖北宇凰德育健康咨询有限公司','http://www.hbyhgxy.com/','地址: 湖北省武汉市江夏区乌龙泉街','https://tieba.baidu.com/p/8102952358→百度搜索 || CTSN','UNKNOWN','https://tieba.baidu.com/p/8102952358','100','FALSE');
INSERT INTO INSTITUTE_LIST VALUES('E54A3F01','湖南智优戒网瘾学校','UNKNOWN','UNKNOWN','知乎搜索->https://zhuanlan.zhihu.com/p/355502237','UNKNOWN','NONE','UNKNOWN','FALSE');
INSERT INTO INSTITUTE_LIST VALUES('D0416B47','岳阳善一学校','(推测而得)(无法正常访问)http://www.yyshanyi.com/','UNKNOWN','https://tieba.baidu.com/p/8102952358→知乎搜索→https://zhuanlan.zhihu.com/p/355502237→DuckDuckGo搜索','UNKNOWN','NONE','UNKNOWN','FALSE');
INSERT INTO INSTITUTE_LIST VALUES('1F93939A','重庆沙坪坝区歌乐山新启点兵仪素质教育中心(重庆新启点学生素质教育基地)','UNKNOWN','重庆市沙坪坝区中梁镇新兴路8号(重庆立事信息工程学校B区北侧)','https://tieba.baidu.com/p/7582101377 || CTSN','UNKNOWN','https://tieba.baidu.com/p/7582101377','100','FALSE');
INSERT INTO INSTITUTE_LIST VALUES('36B30057','李锋教育','(推测而得)(无法正常访问)http://hnlfjy.com/','UNKNOWN','https://tieba.baidu.com/p/8118308647→百度搜索','UNKNOWN','NONE','UNKNOWN','FALSE');
INSERT INTO INSTITUTE_LIST VALUES('586AC90D','济南纳川 || 济南纳川心理教育咨询有限公司','http://www.ncxljy.com/','济南市市中区党家庄镇府对过','https://tieba.baidu.com/p/7426397676→百度搜索','UNKNOWN','NONE','UNKNOWN','FALSE');
INSERT INTO INSTITUTE_LIST VALUES('243CB262','广西德馨励志教育|| 德馨励志教育 || 广西德馨励志教育文化传播有限公司','http://www.777jwy.com/','广西南宁市兴宁区长堽路四里113号; 分校: 广西壮族自治区河池市巴马县巴马镇赐福村江良屯广西德馨励志巴马分校(原江良小学)','https://tieba.baidu.com/p/7216862421→百度搜索 || CTSN','yes','NONE','200','FALSE');
INSERT INTO INSTITUTE_LIST VALUES('56694384','西安弘毅网瘾戒除训练学校','UNKNOWN','UNKNOWN','https://tieba.baidu.com/p/7464866957','UNKNOWN','https://tieba.baidu.com/p/7464866957','UNKNOWN','FALSE');
INSERT INTO INSTITUTE_LIST VALUES('20DD2DAD','成都赏美素质教育 || (→)都德尚美素质教育','(推测而得)(无法正常访问)http://www.cdsmjy.com/','UNKNOWN','https://tieba.baidu.com/p/7526480568→百度搜索→https://tieba.baidu.com/p/7526480568','UNKNOWN','https://zhuanlan.zhihu.com/p/601750315','UNKNOWN','FALSE');
INSERT INTO INSTITUTE_LIST VALUES('22190597','成都精诚弘毅拓展训练公司','UNKNOWN','UNKNOWN','https://tieba.baidu.com/p/7526480568→百度搜索→https://tieba.baidu.com/p/7526480568','UNKNOWN','https://zhuanlan.zhihu.com/p/601750315','UNKNOWN','FALSE');
INSERT INTO INSTITUTE_LIST VALUES('3AE2036B','成都励志宏源拓展训练公司','UNKNOWN','UNKNOWN','https://tieba.baidu.com/p/7526480568→百度搜索→https://tieba.baidu.com/p/7526480568','UNKNOWN','https://zhuanlan.zhihu.com/p/601750315','UNKNOWN','FALSE');
INSERT INTO INSTITUTE_LIST VALUES('DC81A5B6','济南市宏开教育培训学校','https://jinan.dzwww.com/ztzh/hkxx/','济南市','https://tieba.baidu.com/p/7131688961→百度搜索→DuckDuckGo搜索','TRUE','https://baijiahao.baidu.com/s?id=1686529077698052025 || https://www.thepaper.cn/newsDetail_forward_10446063','UNKNOWN','FALSE');
INSERT INTO INSTITUTE_LIST VALUES('A20C4B3A','合肥厚德教育咨询有限公司 || 德厚教育基地','http://hfhdedu.com/','UNKNOWN','网友私信','UNKNOWN','NONE','UNKNOWN','FALSE');
INSERT INTO INSTITUTE_LIST VALUES('687083F1','凯越励志教育','UNKNOWN','广西省七星区寨山脚','https://tieba.baidu.com/p/7804910705','UNKNOWN','https://tieba.baidu.com/p/7804910705','UNKNOWN','FALSE');
INSERT INTO INSTITUTE_LIST VALUES('20DA2E24','志华特训学校 || 志华教育 || 志华教育咨询有限公司','http://www.zhczxx.com/ || http://www.hnzhihua.com/','志华特训学校地址: 湖南省长沙市望城区乔口镇柏乐园附近','ASaferChina (channel)@Telegram || 知乎搜索->https://zhuanlan.zhihu.com/p/555295501->DuckDuckGo搜索','UNKNOWN','NONE','UNKNOWN','FALSE');
INSERT INTO INSTITUTE_LIST VALUES('5AC8FEEF','萃华实验学校 || 萃华青少年特训学校','http://www.cuihuajy.com/','地址: 安徽省六安市','知乎搜索->https://zhuanlan.zhihu.com/p/555295501→DuckDuckGo搜索','UNKNOWN','NONE','UNKNOWN','FALSE');
INSERT INTO INSTITUTE_LIST VALUES('C22CDFC8','徐州习正教育','UNKNOWN','UNKNOWN','知乎搜索->https://www.zhihu.com/question/301837316/answer/1969644263','UNKNOWN','https://www.zhihu.com/question/301837316/answer/1969644263 || https://www.zhihu.com/question/301837316/answer/718977461','UNKNOWN','FALSE');
INSERT INTO INSTITUTE_LIST VALUES('DD27A96B','志和教育','http://www.zhihejiaoyu.com','湖南省长沙市长沙县C17A与Y316交叉口西北方向180米','百度搜索 || CTSN','yes','NONE','500+','FALSE');
INSERT INTO INSTITUTE_LIST VALUES('87EA0028','成才励志教育学校','UNKNOWN','湖南省益阳市资阳区成才励志教育培训学校','https://www.zhihu.com/people/63-11-90-1','TRUE','https://web.archive.org/web/20230507181159/https://twitter.com/ChrysalisQWQ/status/1655163765799931906','UNKNOWN','FALSE');
INSERT INTO INSTITUTE_LIST VALUES('F2B43244','济南市纽扣青少年心理成长基地 || 纽扣青少年教育学校 || 济南市长清区纽扣教育培训学校有限公司','https://www.nukoschool.com/ || http://www.niukoujiaoyu.com/ || http://www.sdnuko.com/','济南市长清区纽扣教育培训学校有限公司 || 济南市长清区张夏镇高庄村','网友私信 || CTSN','UNKNOWN','NONE','100','FALSE');
INSERT INTO INSTITUTE_LIST VALUES('8DB98812','耀昂青少年素质教育','UNKNOWN','(推测而得)重庆市','网友私信','UNKNOWN','NONE','UNKNOWN','FALSE');
INSERT INTO INSTITUTE_LIST VALUES('BDBFC08B','泉州市四维未成年人成长指导中心','UNKNOWN','福建省泉州市晋江市英林镇嘉排村135号','网友私信','UNKNOWN','NONE','UNKNOWN','FALSE');
INSERT INTO INSTITUTE_LIST VALUES('9DDDD791','永州市零陵县立德培训学校','https://space.bilibili.com/2048903183','湖南省永州市零陵区邮亭圩镇雷家亭村','Michelle Chan的「中国大陆“扭转机构”/“叛逆孩子特训学校”名单」 || CTSN','UNKNOWN','NONE','100','FALSE');
INSERT INTO INSTITUTE_LIST VALUES('5385AD5F','永州市零陵区中博青少年培训学校','https://www.douyin.com/user/MS4wLjABAAAA1VsnTENIMZdeuhZNZjdbbR1c6US-e215644oYV8BB0M','永州市零陵区珠山镇田心村','Michelle Chan的「中国大陆“扭转机构”/“叛逆孩子特训学校”名单」','UNKNOWN','NONE','UNKNOWN','FALSE');
INSERT INTO INSTITUTE_LIST VALUES('0A313578','岳阳市湘阴县圣博青少年成长培训学校（慧腾园区）','UNKNOWN','岳阳市湘阴县袁家铺镇沙湖村','Michelle Chan的「中国大陆“扭转机构”/“叛逆孩子特训学校”名单」','TRUE','https://x.com/yaming00742313/status/1824809430736867503 || https://www.bilibili.com/video/BV1D2421Z7Mj/ || https://www.bilibili.com/video/BV1wop6eqEQk/','UNKNOWN','FALSE');
INSERT INTO INSTITUTE_LIST VALUES('B41AC61D','岳阳市湘阴县圣博青少年成长培训学校（中山园区）','UNKNOWN','岳阳市湘阴县东塘镇小桥村湘营路','Michelle Chan的「中国大陆“扭转机构”/“叛逆孩子特训学校”名单」','UNKNOWN','NONE','UNKNOWN','FALSE');
INSERT INTO INSTITUTE_LIST VALUES('1014DD56','江永县振新青少年专门学校','UNKNOWN','江永县潇浦镇车田村车田村委会旁','Michelle Chan的「中国大陆“扭转机构”/“叛逆孩子特训学校”名单」 || CTSN','UNKNOWN','NONE','100','FALSE');
INSERT INTO INSTITUTE_LIST VALUES('FD08A135','湖南全德青少年教育','https://www.hnquande.com/','湖南省石门县夹山镇三板桥全德特训基地','Michelle Chan的「中国大陆“扭转机构”/“叛逆孩子特训学校”名单」','UNKNOWN','NONE','UNKNOWN','FALSE');
INSERT INTO INSTITUTE_LIST VALUES('C6F246D5','四川新巴蜀青少年特训学校 || 新巴蜀特训营','(推测而得)(无法正常访问)http://www.xinbashu.cn/','成都新都区军屯镇','B站视频->Bing搜索','TRUE','https://www.bilibili.com/video/BV1uZ421K7NJ/ || https://news.cctv.com/2024/08/18/ARTIjq41Ia4U5awvNCpsW5GU240818.shtml || https://www.bilibili.com/video/BV1jE4m1d7ws/ || https://www.bilibili.com/video/BV1n5WHejEr7/','UNKNOWN','FALSE');
INSERT INTO INSTITUTE_LIST VALUES('72B1B2FF','励萱教育叛逆戒网瘾学校 || 励萱教育','https://www.peixun123.com/lxjypnjwyxx','(不确定)(注册地址)河南省三门峡市城乡一体化示范区禹王路街道北朝村村委会院内05号','Michelle Chan的「中国大陆“扭转机构”/“叛逆孩子特训学校”名单」','UNKNOWN','NONE','UNKNOWN','FALSE');
INSERT INTO INSTITUTE_LIST VALUES('E441C30D','长沙旭阳教育','UNKNOWN','湖南省长沙县星沙街道开元中路88号星隆国际广场1栋1601','Michelle Chan的「中国大陆“扭转机构”/“叛逆孩子特训学校”名单」','UNKNOWN','NONE','UNKNOWN','FALSE');
INSERT INTO INSTITUTE_LIST VALUES('84CE2EEB','重庆旭阳教育','https://www.100jiaoyu.com/xyjy/','重庆市铜梁区东城街道办事处安全村六组','Michelle Chan的「中国大陆“扭转机构”/“叛逆孩子特训学校”名单」','UNKNOWN','NONE','UNKNOWN','FALSE');
INSERT INTO INSTITUTE_LIST VALUES('3272330A','重庆护航学生素质训练基地','https://www.guanwenw.com/cqhhjy','重庆市渝北区玉峰山镇','Michelle Chan的「中国大陆“扭转机构”/“叛逆孩子特训学校”名单」','UNKNOWN','NONE','UNKNOWN','FALSE');
INSERT INTO INSTITUTE_LIST VALUES('B3D8904D','重庆志强素质教育','UNKNOWN','重庆市渝北区玉峰山镇','Michelle Chan的「中国大陆“扭转机构”/“叛逆孩子特训学校”名单」','UNKNOWN','NONE','UNKNOWN','FALSE');
INSERT INTO INSTITUTE_LIST VALUES('7E292661','白领尔教育','http://ble.cn7q.cn/','重庆市','Michelle Chan的「中国大陆“扭转机构”/“叛逆孩子特训学校”名单」','UNKNOWN','NONE','UNKNOWN','FALSE');
INSERT INTO INSTITUTE_LIST VALUES('2013565C','重庆胤辰素质教育','https://www.douyin.com/user/MS4wLjABAAAA-xUEj7CnMtyL3ub84bJMRUuSulQEPshr3Kdw9KEWLGA','(实际位置很可能位于金佛山国家级风景名胜区内)重庆市南川区南城街道庆岩社区5组100号','Michelle Chan的「中国大陆“扭转机构”/“叛逆孩子特训学校”名单」','TRUE','https://www.douyin.com/video/7404091671505308966','UNKNOWN','FALSE');
INSERT INTO INSTITUTE_LIST VALUES('F3D5347A','重庆子龙素质教育','https://www.douyin.com/user/MS4wLjABAAAAeWZXi30I9iZl2zXlu6FZJu-CkwTfml4OrCpVElbVQUOPeWCKlsYJP8Yz0uirXAE1','重庆市','Michelle Chan的「中国大陆“扭转机构”/“叛逆孩子特训学校”名单」','UNKNOWN','NONE','UNKNOWN','FALSE');
INSERT INTO INSTITUTE_LIST VALUES('0A18A48D','凤凰县文武学校 || 凤凰文武学校','https://www.douyin.com/user/MS4wLjABAAAApfjMXTsjtsywIAYBxmmgGHKPdjWJ338sEDbUCHa48rP1QEHK7Dc5OSiryXSDS6Hz','湖南省湘西土家族苗族自治州凤凰县廖家桥镇廖潭公路旁','抖音搜索"叛逆孩子学校" || CTSN','TRUE','NONE','500+','FALSE');
INSERT INTO INSTITUTE_LIST VALUES('DC1B0F6A','途领跑素质教育 || 重庆途领跑拓展训练有限公司','https://www.douyin.com/user/MS4wLjABAAAARgKTU-OdTNE4hIa6roQyu10vZlHupWErMbLawVO42WkC0LqZI9Sp9pNzdhTDPzO3','重庆市','抖音搜索"叛逆孩子学校"','UNKNOWN','NONE','UNKNOWN','FALSE');
INSERT INTO INSTITUTE_LIST VALUES('DC9983B3','长思-青少年素质教育成长中心 || 河南长思教育科技有限公司','https://www.douyin.com/user/MS4wLjABAAAA62B2ZxH_MmmumL7iETqmVK39Yuy2r1F5vQWYANIlgn0','UNKNOWN','抖音搜索"叛逆孩子学校"','UNKNOWN','NONE','UNKNOWN','FALSE');
INSERT INTO INSTITUTE_LIST VALUES('81E0C008','衡东少林文武学校','https://www.douyin.com/user/MS4wLjABAAAAHeKeYONiWA9F4zwA3OsCja0b85yogbkvhBAwhN3Myrs || https://www.douyin.com/user/MS4wLjABAAAA8sDGdNlfCQd9STC7622VLtKNgXv_xc1OV4IDsH3Gvv2-XKP9RAQCiMKOUc_JTds7 || https://www.douyin.com/user/MS4wLjABAAAAcSSO_Nai8UmGtU1ySbvbJ6RnQKa5IO9fFONePpZ8-oU || https://www.douyin.com/user/MS4wLjABAAAAlTugT6rECPZiqch_EFDnQCMK2uhXO5JkR_IOYTNr-n4','湖南省衡阳市衡东县衡山大道与X007交叉路口往东南约130米','抖音搜索"叛逆孩子学校"->抖音搜索"衡东少林文武学校" || CTSN','TRUE','NONE','200','FALSE');
INSERT INTO INSTITUTE_LIST VALUES('A730910A','青优特训教育信息咨询中心','https://www.douyin.com/user/MS4wLjABAAAAkhtcAjDnQAxIqAOklN0YkGNGz_XU3l4y7kgOf8Yx0o2zoFyZvCDvWx8SKC10IMI5','UNKNOWN','抖音搜索"叛逆孩子学校"','UNKNOWN','NONE','UNKNOWN','FALSE');
INSERT INTO INSTITUTE_LIST VALUES('9C99C073','德立青少年素质教育 || 德立学校 || 德立素质教育 || 德立教育 || 德立（叛逆）学校','https://www.douyin.com/user/MS4wLjABAAAAk9NNbbAXgAHfLIFULp3OVSdEHsjQvvHdnfILDy-wY1c || https://www.douyin.com/user/MS4wLjABAAAAq_sv2nD38ljwrPiNprLyq_QIxtUpmSSnF5-M8bafpYSPHRIJIrKoUAbUbN0TK8uJ || https://www.douyin.com/user/MS4wLjABAAAAimYhLmJG_lRfVw12f5guQktRySB4UiWm4iaaYep5wTc || https://www.douyin.com/user/MS4wLjABAAAA4oAUV0gaMFLuKD4-NtEe4jNfv1ut5ZSTacgK3-_tHcfaqpS-6prAdNHaaMDu3i7Z || https://www.douyin.com/user/MS4wLjABAAAABPVhvP3hhsL1LnmQwalXjWoVVqdUe6t52D-RI9rduCmun4ceZ9l1tpgzWHTQpu03','UNKNOWN','抖音搜索"戒网瘾学校"->抖音搜索"德立教育叛逆学校"','UNKNOWN','NONE','UNKNOWN','FALSE');
INSERT INTO INSTITUTE_LIST VALUES('92A8E742','励思素质特训','https://www.douyin.com/user/MS4wLjABAAAAo507g66_T7BJ-INS7zEVJKrgFx1AIAG3S9HLIn9iCdEKAEiUAfhglxiRuTC4qcU1','UNKNOWN','抖音搜索"青春期孩子学校"','UNKNOWN','NONE','UNKNOWN','FALSE');
INSERT INTO INSTITUTE_LIST VALUES('A03E7ADB','揭阳市天天向上教育基地','https://www.douyin.com/user/MS4wLjABAAAARkutoShJl7FfGcJKFNaq88i7DoPPuIX4O3kv_B4G-ZA','(推测而得)揭阳市','抖音搜索"青春期孩子学校"','UNKNOWN','NONE','UNKNOWN','FALSE');
INSERT INTO INSTITUTE_LIST VALUES('A29AF926','启点少年管教咨询 || 湖北启点教育投资有限公司','https://www.douyin.com/user/MS4wLjABAAAAgtXKV7gIK6R51FwPlkRMzvCMRUHavDnMLepevmHaEaiIqGffKoH6n4Nz8YG_2KYV','UNKNOWN','抖音搜索"青春期孩子学校"','UNKNOWN','NONE','UNKNOWN','FALSE');
INSERT INTO INSTITUTE_LIST VALUES('4F522085','励志教育特训-子翔 || 河南子翔励志教育咨询有限公司','https://www.douyin.com/user/MS4wLjABAAAAqSezIMK8GWRnp-Zxjir7Paf-UAWinFjd65HJ7NJjX7MuuE5KV8XkKs6ncgj49lIX','UNKNOWN','抖音搜索"青春期孩子学校"','UNKNOWN','NONE','UNKNOWN','FALSE');
INSERT INTO INSTITUTE_LIST VALUES('70D5B632','思佳咨询中心 || 郑州郑东新区思佳信息咨询中心','https://www.douyin.com/user/MS4wLjABAAAAhSOWvAEADhAm-pXMCBM3-9T_YkKFyo6DRIR-TIBsLePrJyyAJIIor3F1jm_5HMqf','UNKNOWN','抖音搜索','UNKNOWN','NONE','UNKNOWN','FALSE');
INSERT INTO INSTITUTE_LIST VALUES('F186C82A','国瑾教育','https://www.douyin.com/user/MS4wLjABAAAAVusxBvzxDd14lB1HgzNMomTONt_97JoPzcHJssVytBw','UNKNOWN','抖音搜索"青春期孩子学校"','UNKNOWN','NONE','UNKNOWN','FALSE');
INSERT INTO INSTITUTE_LIST VALUES('BF502CCE','五博叛逆孩子成长教育','https://www.kuaishou.com/profile/3x4f65iudbxaxa9','UNKNOWN','快手搜索用户"叛逆孩子"','UNKNOWN','NONE','UNKNOWN','FALSE');
INSERT INTO INSTITUTE_LIST VALUES('1A3CD6D4','护苗教育','https://www.kuaishou.com/profile/3x7bu7ttex2cbha','UNKNOWN','快手搜索用户"叛逆孩子"','UNKNOWN','NONE','UNKNOWN','FALSE');
INSERT INTO INSTITUTE_LIST VALUES('C69CD308','碧海教育','https://www.douyin.com/user/MS4wLjABAAAA_1dcn7pZ-7ZMchIdn19WNpruxMlYOYNR9cNax5gkQCqXisq9anCJGCNDgidAoH7R','UNKNOWN','抖音搜索"青春期孩子学校"','UNKNOWN','NONE','UNKNOWN','FALSE');
INSERT INTO INSTITUTE_LIST VALUES('937CBC99','许絮教育信息咨询','https://www.douyin.com/user/MS4wLjABAAAAKl5bHdEdzPq2HfFpnhhkNyrz93_YxhdLEWGdzAhiS5o7urcV0Lmk_Goh4LkxroGn','UNKNOWN','抖音搜索"青春期孩子学校"','UNKNOWN','NONE','UNKNOWN','FALSE');
INSERT INTO INSTITUTE_LIST VALUES('F3B5C10D','商丘初心研学教育基地 || 商丘初心研学教育','https://www.douyin.com/user/MS4wLjABAAAAgxpbvTASbU1HDSMA15dCic0rqbvFdlgpb3_IGNA0Vh0 || https://www.douyin.com/user/MS4wLjABAAAADPuhlnSDTQrGjo_x5KYhdy3O9Qk8idUFXrByENBJ3NhTbwgB-YxKvflEXzZJp71g','河南商丘','抖音搜索"问题孩子学校"->抖音搜索"商丘初心研学教育"','UNKNOWN','NONE','UNKNOWN','FALSE');
INSERT INTO INSTITUTE_LIST VALUES('AC33BE08','星启航少年管教咨询 || 星启航教育 || 湖北星启航教育咨询有限公司','https://www.douyin.com/user/MS4wLjABAAAA56T58wri_muOfxcpW3ZPJu4sCvpvqyqgWymCF_pJzlPM3s0ls-n6erYrEjKvsZH5','UNKNOWN','抖音搜索"问题孩子学校"','UNKNOWN','NONE','UNKNOWN','FALSE');
INSERT INTO INSTITUTE_LIST VALUES('C9AF1C9D','揭阳东美实验专门教育矫正学校 || 东美实验叛逆矫正学校','https://www.douyin.com/user/MS4wLjABAAAAWPiw_efSumglczPrB0XhYdOrqQ4o2r6MZbfMf7Ew0Jc','广东省揭阳市揭东区泰兴路福利楼东南侧约110米','网友私信 || CTSN','TRUE','https://www.bilibili.com/video/BV1kcsce4E5c/','100','FALSE');
INSERT INTO INSTITUTE_LIST VALUES('3870B561','振中特训','https://www.douyin.com/user/MS4wLjABAAAASyM85LPz9nFznHUZHAYH7YkVApwxSAb_946FZO_7LGn6-SrT75DCOVBNJ7X6_1nU','UNKNOWN','抖音搜索"矫正学校"','UNKNOWN','NONE','UNKNOWN','FALSE');
INSERT INTO INSTITUTE_LIST VALUES('292D03E6','汉川市启泰特色教育学校 || 启泰教育 || 启泰特色教育学校','http://www.city-edu.cn/','湖北省汉川市庙头镇','Bing搜索"戒网瘾学校"','UNKNOWN','NONE','UNKNOWN','FALSE');
INSERT INTO INSTITUTE_LIST VALUES('D3CC58FF','博恩青少年教育基地 || 惠州博恩青少年教育成长基地 || 惠州伯乐青少年教育成长基地 || 博恩教育 || 惠州市博恩心理咨询服务有限公司','https://www.gdboquan.com/ || https://www.hzboen.com/','广东省惠州市博罗县罗阳街道义和镇伯乐青少年教育成长基地','Bing搜索"戒网瘾学校"','UNKNOWN','NONE','UNKNOWN','FALSE');
INSERT INTO INSTITUTE_LIST VALUES('430917CD','石嘴山市航正青少年成长中心 || 宁夏航正心理咨询 || 石嘴山市航正心理咨询有限责任公司','http://www.szshz.com/','宁夏回族自治区石嘴山市大武口区贺兰山北路1-23-2 || 宁夏回族自治区-石嘴山市-大武口区-贺兰山北路532号 洗煤厂工业遗址公园对面','网友私信 || CTSN','TRUE','NONE','100','FALSE');
INSERT INTO INSTITUTE_LIST VALUES('A4D215D3','匠学青少年素质教育-湖北潜江 || 匠学青少年素质教育 || 湖北潜江匠学教育','https://www.douyin.com/user/MS4wLjABAAAAMrIk_Xw0zpneySHsTE4KvEHKkPRiGogfFjH035QE9TBH8_8XP39_el8L1z67w4BL','湖北省潜江市周肌街道汉沙路2号','百度贴吧"戒网瘾学校吧"','TRUE','https://tieba.baidu.com/p/9107780287','UNKNOWN','FALSE');
INSERT INTO INSTITUTE_LIST VALUES('4C14AE68','贵州省遵义市直利青少年素质教育中心 || 贵州直利素质教育学校 || 贵州遵义直利教育 || 直利教育','https://www.douyin.com/user/MS4wLjABAAAA0LKtPen24QbnIUocwQCiIrmvHy_19eSAxA9z6EozyKln2S6oSMkn6TNQcmYMxtnY','贵州省遵义市','百度贴吧"戒网瘾学校吧"','TRUE','https://tieba.baidu.com/p/9096358124','UNKNOWN','FALSE');
INSERT INTO INSTITUTE_LIST VALUES('4538BEE8','心海岸青少年叛逆戒网瘾学校 || 成都心海岸教育咨询有限公司','https://www.douyin.com/user/MS4wLjABAAAAicG6FSNVe-DUBgyIcmFuFE28tJLWOwzub-pMj7BOyzIEL4reGMdVdN9xXn-mStqf','UNKNOWN','网上搜索','UNKNOWN','NONE','UNKNOWN','FALSE');
INSERT INTO INSTITUTE_LIST VALUES('7CAC3727','江苏渝铭青少年特训基地','https://www.douyin.com/user/MS4wLjABAAAAcjZG84r4lcy-3zZKrLOIMeSX6H5FDFeCzCm2Dr_UomU','UNKNOWN','抖音搜索"特训基地"','UNKNOWN','NONE','UNKNOWN','FALSE');
INSERT INTO INSTITUTE_LIST VALUES('DCBCE442','心种子教育 || 山东心种子教育基地 || 山东心种子教育咨询有限公司','http://www.sdxinzhongzi.com/ || https://www.douyin.com/user/MS4wLjABAAAAJrf4f22qEDH8ADTHxyooeLhix3zWDtibZqV-bMAbse4 || (疑似)https://www.douyin.com/user/MS4wLjABAAAAGC-58bxzQc8lHGVKJVI8NmCjwR7WYAjTXRnUaf5nQKQNx7jN3ZPIrIOI2dLu_75g','山东潍坊青州市花卉苗木交易中心东500米路北','X平台帖子','UNKNOWN','NONE','UNKNOWN','FALSE');
INSERT INTO INSTITUTE_LIST VALUES('D695F405','信丰成龙素质教育基地 || 赣州市成龙教育咨询服务有限公司','https://www.douyin.com/user/MS4wLjABAAAAw2FxfCwKwj4CUQPSRwEMzb5RIO2f4MaErxbFv2pmbbo','UNKNOWN','抖音搜索用户"素质教育"','UNKNOWN','NONE','UNKNOWN','FALSE');
INSERT INTO INSTITUTE_LIST VALUES('6FD66174','凤凰姐素质教育培训学校 || 凤凰姐素质教育','https://www.douyin.com/user/MS4wLjABAAAAefq6d5Rr11yc-uiXyk-ZMCGxJFBG2SwzbSqUE0uq0kFqtTleJ1z-JtzDB7Ux_NQj || https://www.douyin.com/user/MS4wLjABAAAAHuPA2Zlt1tYOG8JOoyWTkDalH9-Df6I9JSCGfZEziKk69279FGbK-ARHuA25_iZi || https://www.douyin.com/user/MS4wLjABAAAABnaTSMHvoOuptrP-PI9UkFDaAA7mrmggQgl4nghthyZ3zbnLor_YX0v7K4895I3Y','UNKNOWN','抖音搜索用户"素质教育"','UNKNOWN','NONE','UNKNOWN','FALSE');
INSERT INTO INSTITUTE_LIST VALUES('B59C5D5C','翰林青少年训练营 || 睢宁县翰林青少年训练营','https://www.douyin.com/user/MS4wLjABAAAA9kpWFq4Elr1uHA4n8bzsq6E-ljETm_cuJN2St4G9f78','人民西路睢宁县汇文中学西侧 || 睢宁县官山镇','抖音搜索用户"戒网瘾"','UNKNOWN','NONE','UNKNOWN','FALSE');
INSERT INTO INSTITUTE_LIST VALUES('86A6CB67','郴州资兴市德志未来素质教育培训学校 || 资兴市德志未来素质教育培训学校有限公司','https://www.douyin.com/user/MS4wLjABAAAAWkDwsxmHY39M2xOQb-Tca438z3JgCvVLuWUcjggK_I1_Yb4D_SjpnjOXqGvTj2pp','湖南省郴州市资兴市','抖音搜索用户"素质教育"','UNKNOWN','NONE','UNKNOWN','FALSE');
INSERT INTO INSTITUTE_LIST VALUES('95ABAFB0','安徽民德素质学校','http://www.ahminde.cn/','安徽省安庆市怀宁县金拱镇高湖村','Bing搜索" 戒网瘾学校"','UNKNOWN','NONE','UNKNOWN','FALSE');
INSERT INTO INSTITUTE_LIST VALUES('90CD63EC','心阳教育 || 汕头市心阳教育学校','http://www.gdttxs.com/','汕头市潮阳区和平镇安轿村心阳教育基地（原安轿小学）','Bing搜索" 戒网瘾学校"','UNKNOWN','NONE','UNKNOWN','FALSE');
INSERT INTO INSTITUTE_LIST VALUES('ED72BF79','石家庄君泽体能拓展','http://www.sjz020jy.com/','河北省石家庄市栾城区西营乡后牛村大道街东头（308国道东）','Bing搜索" 戒网瘾学校"','UNKNOWN','NONE','UNKNOWN','FALSE');
INSERT INTO INSTITUTE_LIST VALUES('59BEED72','长沙市雨花区快乐成长培训学校','http://www.klczxx.cn/','湖南省长沙市雨花区','Bing搜索" 戒网瘾学校"','UNKNOWN','NONE','UNKNOWN','FALSE');
INSERT INTO INSTITUTE_LIST VALUES('CF23C63D','德智体能拓展 || 南通德智体能机构 || 南通德智体能拓展有限公司','http://www.dztnedu.cn/','江苏省如皋市城北街道双龙居德智体能拓展','Bing搜索" 戒网瘾学校"','UNKNOWN','NONE','UNKNOWN','FALSE');
INSERT INTO INSTITUTE_LIST VALUES('B74A5400','孔德青少年特训学校','(疑似)http://www.jikebon.com/school/80.html','UNKNOWN','Bing搜索"特训学校"','UNKNOWN','NONE','UNKNOWN','FALSE');
INSERT INTO INSTITUTE_LIST VALUES('A3BD141D','重庆尚爱拓展训练基地','UNKNOWN','重庆市巴南区南泉街道','CTSN','TRUE','NONE','50~100','FALSE');
INSERT INTO INSTITUTE_LIST VALUES('6CDFABD0','重庆如仁教育','UNKNOWN','重庆市大足区棠香街道双丰村10组19号','CTSN','TRUE','NONE','100','FALSE');
INSERT INTO INSTITUTE_LIST VALUES('C93FF436','长沙县回龙文武学校','UNKNOWN','湖南省长沙市长沙县梁坪村','CTSN','TRUE','NONE','200','FALSE');
INSERT INTO INSTITUTE_LIST VALUES('091691E9','长沙启徳励志特训学校','UNKNOWN','湖南省长沙市开福区湘绣文化小镇(沙坪湘绣城旁)','CTSN','TRUE','NONE','100','FALSE');
INSERT INTO INSTITUTE_LIST VALUES('CD6628DD','运城市国防教育基地','UNKNOWN','山西省运城市南山柏口窑','CTSN','TRUE','NONE','100','FALSE');
INSERT INTO INSTITUTE_LIST VALUES('4EAA3690','永州市零陵区护航学校','UNKNOWN','湖南省永州市零陵区梳子铺乡排龙山村','CTSN','TRUE','NONE','200','FALSE');
INSERT INTO INSTITUTE_LIST VALUES('FF3613C7','宜春博智心理咨询疏导基地','UNKNOWN','江西省宜春市袁州区','CTSN','TRUE','NONE','200','FALSE');
INSERT INTO INSTITUTE_LIST VALUES('E354FA36','沿河启航户外拓展有限公司','UNKNOWN','贵州省铜仁市沿河土家族自治县公安局中界派出所西侧约170米','CTSN','TRUE','NONE','100','FALSE');
INSERT INTO INSTITUTE_LIST VALUES('6FFF53D1','兴仁市仁德学校','UNKNOWN','贵州省兴仁市巴铃镇绿荫社区大坪组','CTSN','TRUE','NONE','100','FALSE');
INSERT INTO INSTITUTE_LIST VALUES('3A7FA2AE','湘龙教育集团(福建宁化校区)','UNKNOWN','福建省三明市宁化县淮土镇凤山村罗家边20号','CTSN','TRUE','NONE','200','FALSE');
INSERT INTO INSTITUTE_LIST VALUES('61F6F2FB','咸宁子龙文武学校','UNKNOWN','湖北省咸宁市咸安区文笔路青龙山关音巷42号','CTSN','TRUE','NONE','200','FALSE');
INSERT INTO INSTITUTE_LIST VALUES('E8901B92','西安护航教育咨询有限公司','UNKNOWN','陕西省西安市蓝田县峣山路','CTSN','TRUE','NONE','300','FALSE');
INSERT INTO INSTITUTE_LIST VALUES('BFA92D79','天阔·向荣励志教育','UNKNOWN','广西壮族自治区南宁市青秀区G324','CTSN','TRUE','NONE','200','FALSE');
INSERT INTO INSTITUTE_LIST VALUES('DC050F3A','唐山森太学校','UNKNOWN','河北省唐山市路北区河东路31号','CTSN','TRUE','NONE','300','FALSE');
INSERT INTO INSTITUTE_LIST VALUES('2DA4F321','思图励志教育学校绍兴青优基地','UNKNOWN','浙江省绍兴市越城区皋埠街道集体村普乐迪技术学院思图励志(青优基地)','CTSN','TRUE','NONE','300','FALSE');
INSERT INTO INSTITUTE_LIST VALUES('E003760C','陕西大正青少年素质培训基地','UNKNOWN','陕西省咸阳市西咸新区沣东新城创新二路36号','CTSN','TRUE','NONE','100','FALSE');
INSERT INTO INSTITUTE_LIST VALUES('E90A2EB9','山东起点军事教育','UNKNOWN','山东省菏泽市临城路','CTSN','TRUE','NONE','100','FALSE');
INSERT INTO INSTITUTE_LIST VALUES('A2436F98','青少年素质教育基地(北辰学院)','UNKNOWN','海南省白沙黎族自治县万宁市山根镇','CTSN','TRUE','NONE','200','FALSE');
INSERT INTO INSTITUTE_LIST VALUES('358965AD','陇南市青少年军校','UNKNOWN','甘肃省陇南市武都区钟楼路长安园西侧约240米','CTSN','TRUE','NONE','100','FALSE');
INSERT INTO INSTITUTE_LIST VALUES('78E6BAB3','临湘市文武职业学校','UNKNOWN','湖南省岳阳市临湘市塘坡巷38','CTSN','TRUE','NONE','300','FALSE');
INSERT INTO INSTITUTE_LIST VALUES('4124E9D3','辽宁正德青少年特训基地','UNKNOWN','辽宁省铁岭市开原市G505(彰桓线)','CTSN','TRUE','NONE','100','FALSE');
INSERT INTO INSTITUTE_LIST VALUES('D6371FFC','兰州德优教育','UNKNOWN','甘肃省兰州市青白石街道大浪沟154号上三百米','CTSN','TRUE','NONE','50','FALSE');
INSERT INTO INSTITUTE_LIST VALUES('F0EA47A0','俭德教育','UNKNOWN','吉林省长春市二道区东河东路与英俊西街交叉路口往东北约100米','CTSN','TRUE','NONE','100','FALSE');
INSERT INTO INSTITUTE_LIST VALUES('9F78C035','嘉禾县文武专门学校','UNKNOWN','湖南省郴州市嘉禾县坦坪镇坦坪村','CTSN','TRUE','NONE','300','FALSE');
INSERT INTO INSTITUTE_LIST VALUES('FBEAAC83','惠州伯恩青少年教育成长基地','UNKNOWN','广东省惠州市惠城区大良村','CTSN','TRUE','NONE','100','FALSE');
INSERT INTO INSTITUTE_LIST VALUES('31687463','黄冈素励教育学校','UNKNOWN','湖北省黄冈市黄州区外甥路','CTSN','TRUE','NONE','100','FALSE');
INSERT INTO INSTITUTE_LIST VALUES('B33A77B8','湖南南华学校','UNKNOWN','湖南省永州市宁远县216省道东100米','CTSN','TRUE','NONE','300','FALSE');
INSERT INTO INSTITUTE_LIST VALUES('4B25D061','湖北善聆心理教育','UNKNOWN','湖北省随州市广水市杨寨镇丁湾村吴家咀','CTSN','TRUE','NONE','100+','FALSE');
INSERT INTO INSTITUTE_LIST VALUES('5F74C307','衡水乾景健康特训基地','UNKNOWN','河北省衡水市冀州区G106(东湖大道)','CTSN','TRUE','NONE','100-','FALSE');
INSERT INTO INSTITUTE_LIST VALUES('435F2E9F','黑龙江猎人少年军校','UNKNOWN','黑龙江省哈尔滨市道里区利民头道街2号','CTSN','TRUE','NONE','100','FALSE');
INSERT INTO INSTITUTE_LIST VALUES('28521014','河北新航综合素质教育基地','UNKNOWN','河北省廊坊市固安县永定街西曹庄村','CTSN','TRUE','NONE','100','FALSE');
INSERT INTO INSTITUTE_LIST VALUES('5BFF92EC','海南快乐成长学校','UNKNOWN','海南省海口市琼山区长泰路5号','CTSN','TRUE','NONE','200','FALSE');
INSERT INTO INSTITUTE_LIST VALUES('AE951D3E','贵州志扬户外拓展基地','UNKNOWN','贵州省黔西南自治州兴义市万峰林街道','CTSN','TRUE','NONE','100','FALSE');
INSERT INTO INSTITUTE_LIST VALUES('EA76F90D','广西新定义教育','UNKNOWN','广西北流市印塘大道与岑玉线交叉口东南约120米','CTSN','TRUE','NONE','100','FALSE');
INSERT INTO INSTITUTE_LIST VALUES('1B94C8D4','广西南宁兴华教育咨询中心（兴华励志教育）','UNKNOWN','广西壮族自治区南宁市武鸣区百威英博大道与里建大道交叉路口往北约180米','CTSN','TRUE','NONE','200','FALSE');
INSERT INTO INSTITUTE_LIST VALUES('60314349','广西灵山华益学校','UNKNOWN','广西省钦州市灵山县S312广西农村信用社西南侧约220米','CTSN','TRUE','NONE','100','FALSE');
INSERT INTO INSTITUTE_LIST VALUES('EA7B66E4','广东阳江兴华励志学校','UNKNOWN','广东省阳江市广南线X607','CTSN','TRUE','NONE','100','FALSE');
INSERT INTO INSTITUTE_LIST VALUES('0A97D431','赣州市老兵营地训练中心','UNKNOWN','江西省赣州市章贡区五龙三路章贡中学对面','CTSN','TRUE','NONE','100','FALSE');
INSERT INTO INSTITUTE_LIST VALUES('75C7AFD8','丰城市社区矫正基地(龙剑基地)','UNKNOWN','江西省丰城市尚庄街道丰高路8号','CTSN','TRUE','NONE','100','FALSE');
INSERT INTO INSTITUTE_LIST VALUES('9899E1A6','单县明德教育培训学校','UNKNOWN','山东省菏泽市单县单州路','CTSN','TRUE','NONE','100','FALSE');
INSERT INTO INSTITUTE_LIST VALUES('1E2D86F7','赤壁市三国青少年成长学校','UNKNOWN','湖北省咸宁市赤壁赤高黄龙陆逊营寨风景区','CTSN','TRUE','NONE','100+','FALSE');
INSERT INTO INSTITUTE_LIST VALUES('8CBF1B0B','郴州市德志未来学校','UNKNOWN','湖南省郴州市资兴市三都镇Y215','CTSN','TRUE','NONE','200','FALSE');
INSERT INTO INSTITUTE_LIST VALUES('EC16C179','北京兴华励志教育咨询中心','UNKNOWN','北京市顺义区白庙村西胡同41号','CTSN','TRUE','NONE','200','FALSE');
INSERT INTO INSTITUTE_LIST VALUES('C5B9BAA6','北京荣格青少年成长基地','UNKNOWN','北京市大兴区黄村镇刘一村厂前路34号','CTSN','TRUE','NONE','100','FALSE');
INSERT INTO INSTITUTE_LIST VALUES('D0A3B055','安徽卓捷素质教育','UNKNOWN','安徽省蚌埠市怀远县禹风路','CTSN','TRUE','NONE','100','FALSE');
CREATE TABLE RELATED_ARTICLES (
    "ID" TEXT PRIMARY KEY NOT NULL UNIQUE,
    "TITLE" TEXT NOT NULL UNIQUE,
    "ORIGINAL" TEXT NOT NULL UNIQUE,
    "ARCHIVE" TEXT NOT NULL UNIQUE
);
INSERT INTO RELATED_ARTICLES VALUES('2080E731','起底弑母少女身后的网戒学校：暴力抓走、随时体罚和神秘专家','https://www.thepaper.cn/newsDetail_forward_1532141','https://web.archive.org/web/20240616162214/https://www.thepaper.cn/newsDetail_forward_1532141');
INSERT INTO RELATED_ARTICLES VALUES('C37CDA38','网戒学校第一案宣判后，“杨永信”们并没有消失','https://new.qq.com/rain/a/20230612A09QOU00','https://archive.is/RaJ3D');
INSERT INTO RELATED_ARTICLES VALUES('33B97A46','15岁女生在“戒网瘾学校”遭教官性侵，学校封锁丑闻两个月，已被关停','https://new.qq.com/rain/a/20230921A0615D00','https://archive.is/TPKKD');
INSERT INTO RELATED_ARTICLES VALUES('28792DB1','18岁网瘾少年被铐着关禁闭两天死亡，戒网瘾学校5人获刑','https://www.thepaper.cn/newsDetail_forward_3014515','https://archive.is/pbA3c');
INSERT INTO RELATED_ARTICLES VALUES('A3C54CA0','京华时报：“戒网瘾学校”是长在教育上的息肉','http://opinion.people.com.cn/n1/2016/1013/c1003-28774889.html','https://archive.is/kKWiQ');
INSERT INTO RELATED_ARTICLES VALUES('8D9CA466','“戒网瘾死亡”案：母亲称得到血的教训 18岁男孩被送去戒网瘾学校两天后死亡 母亲称得到血的教训','https://www.guancha.cn/politics/2019_02_24_491234.shtml','https://archive.is/VyOLt');
INSERT INTO RELATED_ARTICLES VALUES('55B37DFE','网戒学校20年不倒的秘密：绝对服从，审查家书，不服就打','https://www.thepaper.cn/newsDetail_forward_1540331','https://archive.is/CjWdU');
INSERT INTO RELATED_ARTICLES VALUES('A6034A6F','重审开庭！涉嫌非法拘禁，共19名被害人！揭露人发声→','https://www.thepaper.cn/newsDetail_forward_22537961','https://archive.is/hgHgd');
INSERT INTO RELATED_ARTICLES VALUES('28C4DAF7','一个戒网瘾学校投资者的自白：如何办一所利润100%的“集中营”','https://jiemodui.com/N/94422.html','https://archive.is/XqmzW');
INSERT INTO RELATED_ARTICLES VALUES('1BA20AC3','多名学员讲述新巴蜀特训营经历：被欺凌殴打是常态','https://news.cctv.com/2024/08/18/ARTIjq41Ia4U5awvNCpsW5GU240818.shtml','https://archive.is/GP9bw');
INSERT INTO RELATED_ARTICLES VALUES('426970CF','女生戒网瘾学校内患癌 校方:其父说吃止痛药就行','https://news.sina.com.cn/s/2018-06-15/doc-ihcyszrz8019023.shtml','https://archive.is/J6B1e');
INSERT INTO RELATED_ARTICLES VALUES('4B89FC72','媒体刊文评安徽少年命丧戒网学校：“治网瘾”还要害多少人','https://www.thepaper.cn/newsDetail_forward_1766244','https://archive.is/g2zvr');
INSERT INTO RELATED_ARTICLES VALUES('14281A5D','18岁男孩被送去“戒网瘾”两天后死亡 母亲：很后悔','http://it.people.com.cn/n1/2019/0224/c1009-30898697.html','https://archive.is/KQxXz');
INSERT INTO RELATED_ARTICLES VALUES('84B8D0E4','戒网瘾学校有多恐怖？电击殴打无处不在，学生每天想自杀解脱','https://baijiahao.baidu.com/s?id=1803476657206346381','https://archive.is/cD0gv');
INSERT INTO RELATED_ARTICLES VALUES('5272D25A','14岁男生被送到戒网瘾学校四天后骨折 涉事教官停职 警方介入','https://baijiahao.baidu.com/s?id=1687042964336943370','https://archive.is/CpOtu');
INSERT INTO RELATED_ARTICLES VALUES('09671531','安徽“男孩戒网瘾身亡案”开庭','https://baijiahao.baidu.com/s?id=1614616814979007616','https://archive.is/g5BUx');
INSERT INTO RELATED_ARTICLES VALUES('DF72CE63','山东“戒网瘾学校”：勒令女学员喝脏拖把拧下来的水','https://news.cnr.cn/native/gd/20161014/t20161014_523196309.shtml','https://archive.is/tiOYv');
INSERT INTO RELATED_ARTICLES VALUES('B814FCD9','观点1+1：19岁女孩惨死“野鸡学校”，戒网瘾无正道？','http://opinion.people.com.cn/n/2014/0617/c1003-25161313.html','https://archive.is/vwCNw');
INSERT INTO RELATED_ARTICLES VALUES('BB52CB49','戒网瘾致人死涉事学校仍招生 其办学资格已被撤销','https://finance.cnr.cn/gundong/201406/t20140617_515674809.shtml','https://archive.is/omtwi');
INSERT INTO RELATED_ARTICLES VALUES('F9F976D4','揭秘戒除网瘾学校如何训练和体罚学生：晕倒用水灌','http://www.mnw.cn/news/shehui/763416.html','https://web.archive.org/web/20140906182406/http://www.mnw.cn/news/shehui/763416.html');
INSERT INTO RELATED_ARTICLES VALUES('3B21966B','[共同关注]为戒网瘾 误进"地狱"学校?','https://news.cctv.com/society/20070621/103838.shtml','https://archive.is/rLp9D');
INSERT INTO RELATED_ARTICLES VALUES('D39E40CF','18岁男孩被送去特训学校戒网瘾 不到48小时后身亡','https://news.jstv.com/a/20170814/1502698141724.shtml','https://archive.is/4CRay');
INSERT INTO RELATED_ARTICLES VALUES('79500F42','“电疗”戒网瘾，孩子每天做噩梦想自杀！究竟谁之过？','https://baijiahao.baidu.com/s?id=1597625897292562775','https://archive.is/0HpfW');
INSERT INTO RELATED_ARTICLES VALUES('78190364','我采访了三个从网瘾中心出来的少年 他们到底经历了什么','https://www.guancha.cn/society/2016_08_12_371072_s.shtml','https://archive.is/LbXTa');
INSERT INTO RELATED_ARTICLES VALUES('8603A280','河南19岁少女戒网瘾死在学校特训课上 遍体鳞伤','https://news.rednet.cn/c/2014/06/15/3376711.htm','https://archive.is/ZLszM');
INSERT INTO RELATED_ARTICLES VALUES('8992ED9F','对话因开网店被送网戒中心当事人：“我将站在阳光下，与杨永信对质”','https://new.qq.com/rain/a/20230426A09PBD00','https://archive.is/cNyrw');
INSERT INTO RELATED_ARTICLES VALUES('E8E0BD09','被殴打、遭虐待，曝光特训学校的暗面','https://mp.weixin.qq.com/s/vtG9wZ3K2nKnfZze8zoudg','https://web.archive.org/web/20240830224131/https://mp.weixin.qq.com/s/vtG9wZ3K2nKnfZze8zoudg');
INSERT INTO RELATED_ARTICLES VALUES('77D12FE4','网友举报成都一特训学校殴打学生还冒充民警，当地多部门介入调查','https://baijiahao.baidu.com/s?id=1807514311674536639','https://archive.is/BsnIs');
INSERT INTO RELATED_ARTICLES VALUES('18340D4C','“叛逆学校”被曝对学生扇巴掌喷辣椒水 河南当地教体局：涉事机构关停，学生及相关人员已清退','https://www.dzwww.com/xinwen/shehuixinwen/202305/t20230511_11908310.htm','https://archive.is/xqdtj');
INSERT INTO RELATED_ARTICLES VALUES('E633D0B9','13岁男孩被送特训学校戒网瘾遭猥亵 公安机关已立案，教官被逮捕','http://news.hnr.cn/shxw/article/1/1676179155252342785','https://web.archive.org/web/20230706213838/http://news.hnr.cn/shxw/article/1/1676179155252342785');
INSERT INTO RELATED_ARTICLES VALUES('361BCFFA','特训营岂能成未成年人保护盲区','https://baijiahao.baidu.com/s?id=1807801484984686362','https://archive.is/NWynG');
INSERT INTO RELATED_ARTICLES VALUES('6DADF1CF','教育没有捷径，别再迷信封闭式“特训营”了','https://m.gmw.cn/2024-08/21/content_37512818.htm','https://archive.is/AuFzc');
INSERT INTO RELATED_ARTICLES VALUES('00957282','“戒网瘾”致死致伤惨剧屡现 谁来终结乱象？','https://society.huanqiu.com/article/9CaKrnJXmEC','https://archive.is/KCyBM');
INSERT INTO RELATED_ARTICLES VALUES('FECFB32D','17岁少年的复仇：干掉那个“戒网瘾”学校','https://zhuanlan.zhihu.com/p/210540199','NONE');
INSERT INTO RELATED_ARTICLES VALUES('7B03C8F4','江西戒网瘾学校豫章书院被曝体罚囚禁学生 区政府：处罚追责','https://www.guancha.cn/Education/2017_10_31_432951.shtml','https://web.archive.org/web/20220706221833/https://www.guancha.cn/Education/2017_10_31_432951.shtml');
INSERT INTO RELATED_ARTICLES VALUES('82F11CB5','问题少年教育问题严重，郑州戒网瘾学校竟能连续7年过审','https://www.thepaper.cn/newsDetail_forward_1251759','https://web.archive.org/web/20171201115634/https://www.thepaper.cn/newsDetail_forward_1251759');
INSERT INTO RELATED_ARTICLES VALUES('956903FC','戒网瘾学校9成涉体罚：最快进校8小时就死','https://tech.sina.com.cn/i/2014-06-19/17429446718.shtml','https://web.archive.org/web/20140728180656/https://tech.sina.com.cn/i/2014-06-19/17429446718.shtml');
INSERT INTO RELATED_ARTICLES VALUES('74BD3BC7','山东“戒网瘾学校”被责令整改后仍在招生，称不影响素质教育','https://www.thepaper.cn/newsDetail_forward_1542403','https://web.archive.org/web/20210415023342/https://www.thepaper.cn/newsDetail_forward_1542403');
INSERT INTO RELATED_ARTICLES VALUES('589C19D6','送孩子进戒网瘾学校的父母：特别怕半夜被儿子杀死','https://news.ifeng.com/c/7fa7wKkI0C7','https://web.archive.org/web/20240901024841/https://news.ifeng.com/c/7fa7wKkI0C7');
INSERT INTO RELATED_ARTICLES VALUES('BE57C553','在学校、医生、心理咨询师的推荐下，他们把孩子送入了“戒网瘾学校”｜深度报道','https://mp.weixin.qq.com/s/d-aJ00-nPwmvDdoPqVvgLA','https://web.archive.org/web/20240525083154/https://mp.weixin.qq.com/s/d-aJ00-nPwmvDdoPqVvgLA');
INSERT INTO RELATED_ARTICLES VALUES('FA902252','少女被虐致死 戒网瘾学校是“守护者”还是“摧残者”','https://hn.ifeng.com/hnzhuanti/zhengzhoujiewangxuexiao/','https://web.archive.org/web/20150809005123/https://hn.ifeng.com/hnzhuanti/zhengzhoujiewangxuexiao/');
INSERT INTO RELATED_ARTICLES VALUES('D6E8E98A','少年命丧戒治网瘾学校 专家：应设国家标准','http://it.people.com.cn/n1/2018/0423/c1009-29942868.html','https://web.archive.org/web/20240901030142/http://it.people.com.cn/n1/2018/0423/c1009-29942868.html');
INSERT INTO RELATED_ARTICLES VALUES('FCAF23DB','戒网瘾学校怎成“摧残基地” ——聚焦戒网瘾学校“培训致人死亡”事件','http://zqb.cyol.com/html/2014-06/22/nw.D110000zgqnb_20140622_6-01.htm','https://web.archive.org/web/20240901030515/http://zqb.cyol.com/html/2014-06/22/nw.D110000zgqnb_20140622_6-01.htm');
INSERT INTO RELATED_ARTICLES VALUES('F0B09290','15岁女生在“戒网瘾学校”遭教官性侵｜深度报道','https://www.163.com/dy/article/IF8FPLBH0512BN99.html','https://web.archive.org/web/20231201012955/https://www.163.com/dy/article/IF8FPLBH0512BN99.html');
INSERT INTO RELATED_ARTICLES VALUES('D6B601D9','“雷电法王”杨永信：曾电击6000网瘾少年，如今下场令人唏嘘','https://www.163.com/dy/article/IFVJ31OF0543VRV7.html','https://web.archive.org/web/20240901030843/https://www.163.com/dy/article/IFVJ31OF0543VRV7.html');
INSERT INTO RELATED_ARTICLES VALUES('13C5FEA6','戒网瘾学校有多恐怖？性侵电击殴打无处不在，学生每天想自杀解脱','https://www.163.com/dy/article/HVDTA64Q0553RHMI.html','https://web.archive.org/web/20240901031114/https://www.163.com/dy/article/HVDTA64Q0553RHMI.html');
INSERT INTO RELATED_ARTICLES VALUES('4E90ED68','13岁男孩“戒网瘾”被教官猥亵！孩子有网瘾，父母到底该怎么办？','https://new.qq.com/rain/a/20230705A0806400','https://web.archive.org/web/20240901031543/https://new.qq.com/rain/a/20230705A0806400');
INSERT INTO RELATED_ARTICLES VALUES('C4AF31F8','电击之后，戒网瘾学校还有创新','https://www.ellemen.com/spotlight/a37239444/wangyin-210806/','https://archive.ph/t77bD');
INSERT INTO RELATED_ARTICLES VALUES('4DA27E91','男孩“戒网瘾”身亡：涉事学校系非法办学 5人被拘','https://www.chinacourt.org/article/detail/2017/08/id/2966563.shtml','https://archive.ph/5ncwf');
INSERT INTO RELATED_ARTICLES VALUES('CFECB642','豫章书院“吹哨人”奔走六年：中国还有许多“豫章书院”','https://new.qq.com/rain/a/20230331A0603500','https://archive.ph/F0PH9');
INSERT INTO RELATED_ARTICLES VALUES('B8D9B39F','"戒网瘾"学校被指虐待学生 校方:不这样咋管住他们','https://www.163.com/news/article/D255N6A20001875P.html','https://web.archive.org/web/20240901032548/https://www.163.com/news/article/D255N6A20001875P.html');
INSERT INTO RELATED_ARTICLES VALUES('DFDEE0CB','第一批被送进戒网瘾学校的孩子，现状让人担忧，父母留下终身悔恨','https://baijiahao.baidu.com/s?id=1665194409189337123','https://archive.ph/QpGlZ');
INSERT INTO RELATED_ARTICLES VALUES('072AE27D','弑母少女的失格人生：争吵捅伤父亲，曾被送网戒学校称要报复','https://www.thepaper.cn/newsDetail_forward_1532179','https://web.archive.org/web/20220926134324/https://www.thepaper.cn/newsDetail_forward_1532179');
INSERT INTO RELATED_ARTICLES VALUES('998BD8FD','湖南一戒网瘾机构被举报监视体罚学生，当地教育局：已在整顿','https://www.thepaper.cn/newsDetail_forward_4986152','https://web.archive.org/web/20220924130334/https://www.thepaper.cn/newsDetail_forward_4986152');
INSERT INTO RELATED_ARTICLES VALUES('C2154E68','戒网瘾学校的时代结束了吗','https://finance.sina.cn/insurance/bxzx/2020-12-27/detail-iiznezxs8988495.d.html','https://archive.ph/Rey9L');
INSERT INTO RELATED_ARTICLES VALUES('FB7D274B','那些被送进戒网瘾学校的孩子','https://zhuanlan.zhihu.com/p/47633665','https://web.archive.org/web/20220524012858/https://zhuanlan.zhihu.com/p/47633665');
INSERT INTO RELATED_ARTICLES VALUES('01547919','15岁女生在“戒网瘾学校”遭教官性侵：许多父母病了，却在喂孩子吃药','https://k.sina.com.cn/article_7307634592_1b391a7a001901a4dy.html','https://web.archive.org/web/20240901040221/https://k.sina.com.cn/article_7307634592_1b391a7a001901a4dy.html');
INSERT INTO RELATED_ARTICLES VALUES('F2B11631','19岁少女死于戒网瘾学校 涉事学校办学资质被取消','https://www.rmzxb.com.cn/sqmy/nywy/2014/06/17/340701_1.shtml','https://web.archive.org/web/20240901041115/https://www.rmzxb.com.cn/sqmy/nywy/2014/06/17/340701_1.shtml');
INSERT INTO RELATED_ARTICLES VALUES('09CE6137','长安剑：从电击疗法到豫章书院，为什么戒网瘾逃不出暴力手段','https://www.thepaper.cn/newsDetail_forward_1846729','https://web.archive.org/web/20220430071639/https://www.thepaper.cn/newsDetail_forward_1846729');
INSERT INTO RELATED_ARTICLES VALUES('078D478D','湖南14岁少年入戒网瘾学校三天后腿骨折 学校称其自己崴伤、附近监控未使用','https://www.thepaper.cn/newsDetail_forward_10468634','https://web.archive.org/web/20240901041707/https://www.thepaper.cn/newsDetail_forward_10468634');
COMMIT;
